import type { Metadata } from "next"
import { inter } from "@/app/ui/font"
import "./globals.css"
import Sidebar from "./ui/Sidebar"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} flex `}>
				<Sidebar />
				{children}
			</body>
		</html>
	)
}
